spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/spring6
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
  hikari:
    maximum-pool-size: 10

logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE
        jdbc:
          support:
            JdbcTransactionManager: TRACE